**Step 1: Create a Random Tensor of Shape (4, 6)**

Creating a random tensor using TensorFlow.

In [3]:
import tensorflow as tf

# Create a random tensor of shape (4, 6)
random_tensor = tf.random.uniform(shape=(4, 6), minval=0, maxval=10, dtype=tf.int32)
print("Original Tensor:\n", random_tensor.numpy())

Original Tensor:
 [[5 8 9 5 7 1]
 [9 5 0 8 4 0]
 [1 5 5 8 3 9]
 [3 1 4 8 2 8]]


**Step 2: Find Its Rank and Shape**

Finding the rank of the tensor.

In [4]:
# Step 2: Find the rank and shape of the tensor
rank = tf.rank(random_tensor)
shape = tf.shape(random_tensor)

print("Rank of the tensor:", rank.numpy())
print("Shape of the tensor:", shape.numpy())

Rank of the tensor: 2
Shape of the tensor: [4 6]


**Step 3: Reshape and Transpose the Tensor**

Reshapeing the tensor to (2, 3, 4) and then transposing it to (3, 2, 4).

In [5]:
# Step 3: Reshape the tensor to (2, 3, 4)
reshaped_tensor = tf.reshape(random_tensor, (2, 3, 4))
print("Reshaped Tensor (2, 3, 4):\n", reshaped_tensor.numpy(), "\n")

# Transpose the reshaped tensor to (3, 2, 4)
transposed_tensor = tf.transpose(reshaped_tensor, perm=[1, 0, 2])
print("Transposed Tensor (3, 2, 4):\n", transposed_tensor.numpy(), "\n")

# Print rank and shape after reshaping and transposing
print("Rank after reshaping and transposing:", tf.rank(transposed_tensor).numpy())
print("Shape after reshaping and transposing:", transposed_tensor.shape, "\n")

Reshaped Tensor (2, 3, 4):
 [[[5 8 9 5]
  [7 1 9 5]
  [0 8 4 0]]

 [[1 5 5 8]
  [3 9 3 1]
  [4 8 2 8]]] 

Transposed Tensor (3, 2, 4):
 [[[5 8 9 5]
  [1 5 5 8]]

 [[7 1 9 5]
  [3 9 3 1]]

 [[0 8 4 0]
  [4 8 2 8]]] 

Rank after reshaping and transposing: 3
Shape after reshaping and transposing: (3, 2, 4) 



**Step 4: Broadcast a Smaller Tensor and Add**

Creating a smaller tensor of shape (1, 4) and broadcasting it to match the shape of the larger tensor (3, 2, 4), then performing element-wise addition.

In [6]:
# Step 4: Broadcasting and Adding Tensors
# Create a smaller tensor of shape (1, 4)
small_tensor = tf.constant([[1, 2, 3, 4]], dtype=tf.int32)

# Broadcast the smaller tensor to match the shape of the larger tensor (3, 2, 4)
broadcasted_tensor = tf.broadcast_to(small_tensor, transposed_tensor.shape)
print("Broadcasted Tensor (3, 2, 4):\n", broadcasted_tensor.numpy(), "\n")


# Add the broadcasted tensor to the transposed tensor
result_tensor = transposed_tensor + broadcasted_tensor
print("Result Tensor after Addition:\n", result_tensor.numpy())

Broadcasted Tensor (3, 2, 4):
 [[[1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]]] 

Result Tensor after Addition:
 [[[ 6 10 12  9]
  [ 2  7  8 12]]

 [[ 8  3 12  9]
  [ 4 11  6  5]]

 [[ 1 10  7  4]
  [ 5 10  5 12]]]


**Step 5: Explain Broadcasting in TensorFlow**

Broadcasting in TensorFlow is a process that allows for operations between tensors of differing shapes by automatically adjusting the smaller tensor to match the dimensions of the larger tensor. Here are the rules for broadcasting:

- **Align dimensions:** Begin from the furthest right dimension and proceed to the left.

- **Expand dimensions:** If a tensor has a dimension size of 1, it can be expanded to match the dimension size of the other tensor.

- **Incompatible shapes:** Broadcasting is not possible if the dimensions do not match and neither dimension is 1.

For this task:

The smaller tensor with shape (1, 4) is broadcasted to a shape of (3, 2, 4) by duplicating its values across the first and second dimensions.